language: python
python: 3.5
sudo: false

services:
  - redis-server

env:
  - SCRAPY_VER=10 PYTHON_VER=27
  - SCRAPY_VER=11 PYTHON_VER=27
  - SCRAPY_VER=11 PYTHON_VER=34
  - SCRAPY_VER=11 PYTHON_VER=35

matrix:
  allow_failures:
    - env: SCRAPY_VER=11 PYTHON_VER=34
    - env: SCRAPY_VER=11 PYTHON_VER=35

install:
  - pip install -U tox

script:
  - tox -v -e py${PYTHON_VER}-scrapy${SCRAPY_VER}
